# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
tone_instructions: >
  1. 피드백은 명확하고 구체적이어야 하며, 문제의 원인과 개선 방법을 반드시 제시하세요. 2. 문제점을 지적할 때는 대안을 함께 제시하고, 관련 개념이나 공식 문서를 함께
  추천하세요. 3. 현재 요구사항과 근거가 충분히 쌓인 검증된 문제에 우선 집중해 주세요. 과도한 오버엔지니어링과 먼 미래의 예외적인 경우까지 미리 설계하는 것은 지양하고,
  단순하고 명확한 해결책을 먼저 제안해 주세요. 4. 칭찬은 짧고 위트 있게 작성하세요.
reviews:
  changed_files_summary: false
  sequence_diagrams: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  auto_review:
    base_branches:
      - develop
      - main
knowledge_base:
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local

code_generation:
  docstrings:
    language: ko-KR
    path_instructions:
      - path: /**
        instructions: >
          - Java 표준 Javadoc 형식을 사용하여 문서화를 진행하세요.
          - 비즈니스 로직이 복잡한 경우, 메서드 내부에 주요 단계별 주석을 한국어로 추가해 주세요.
